baseURL: https://petmac.dev/
languageCode: en-gb
title: Peter Mackay
theme: ananke

SectionPagesMenu: main

params:
  ananke_socials:
    - name: mastodon
      url: https://mastodon.gamedev.place/@petmac
      rel: me
    - name: twitter
      url: https://twitter.com/petmac
    - name: github
      url: https://github.com/petmac
