baseURL: https://petmac.dev/
languageCode: en-gb
title: Peter Mackay
theme: hugo-book

SectionPagesMenu: main

params:
  BookSection: "*"
  ananke_socials:
    - name: twitter
      url: https://twitter.com/petmac
    - name: github
      url: https://github.com/petmac
